/* v1002: idle rewards - the welcome-back popup only appears when the bucket is full; otherwise a 🌙 icon on the World map shows how full it is and opens it to collect any time. Run: node dev/simfork/g224_idle_icon.js */
const fs = require("fs"), path = require("path"), assert = require("assert");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require(process.env.PW_PATH || "/opt/npm-tools/node_modules/playwright");
const CHROME = process.env.CHROME_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const FAKE = fs.readFileSync(path.join(ROOT, "dev/tests/fakefb.js"), "utf8"), GAME = fs.readFileSync(process.env.GAMEFILE || path.join(ROOT, "test/index.html"), "utf8");
const store = {}, call = require(path.join(ROOT, "dev/tests/fnrunner.js"))(store);
(async () => {
  const b = await chromium.launch({ executablePath: CHROME, args: ["--no-sandbox"] }), errs = [];
  const ctx = await b.newContext({ viewport: { width: 430, height: 932 } });
  await ctx.exposeFunction("__fbstore", (op, k, v) => { if (op === "set") store[k] = JSON.parse(v); else if (op === "del") delete store[k]; return JSON.stringify(store); });
  await ctx.exposeFunction("__fbcall", call);
  await ctx.route(/mojojo82\.github\.io/, (r) => r.fulfill({ status: 200, contentType: "text/html", body: GAME }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: FAKE }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*(auth|firestore|functions)-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: "" }));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
  const P = await ctx.newPage(); P.on("pageerror", (e) => errs.push(e.message));
  await P.goto("https://mojojo82.github.io/kingdom-strategy/test/"); await P.waitForSelector("#ksAuth .box");
  await P.fill("#ksE", "g224@test.dev"); await P.fill("#ksP", "secret123"); await P.click("#ksUp");
  await P.waitForSelector("#ksN", { timeout: 15000 }); await P.fill("#ksN", "Emp"); await P.click("#ksGo"); await P.waitForTimeout(5000);
  await P.evaluate(() => setScreen("world")); await P.waitForTimeout(1500);
  const away = (h) => P.evaluate(async (h) => { const st = game.state; st.bucket.en = 0; st.bucket.val = 0; delete st.bucket.away; window.ksWelcomeBackCooldownReset && window.ksWelcomeBackCooldownReset();
    st.bucket.at = Date.now() - h * 3600e3; let shows = 0; for (let i = 0; i < 12; i++) { await new Promise((r) => setTimeout(r, 500)); const p = document.getElementById("wbPop"); if (p && p.style.display === "flex") { shows++; break; } } return shows; }, h);
  const o = {};
  o.pop2h = await away(2); await P.waitForTimeout(2500);
  o.icon = await P.evaluate(() => { const b = document.getElementById("mapIdleBtn"); const r = b.getBoundingClientRect(); return { vis: getComputedStyle(b).display !== "none" && r.width > 0, has: b.classList.contains("has"), full: b.classList.contains("full"), bar: b.querySelector(".mib i").style.width, title: b.title }; });
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "idle_icon.png" });
  const e0 = await P.evaluate(() => Math.floor(game.state.energon));
  await P.click("#mapIdleBtn"); await P.waitForTimeout(300);
  o.popTxt = await P.evaluate(() => document.getElementById("wbPop").innerText);
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "idle_open.png" });
  await P.click("#wbBtn"); await P.waitForTimeout(2500);
  o.gained = (await P.evaluate(() => Math.floor(game.state.energon))) - e0;
  o.after = await P.evaluate(() => { const b = document.getElementById("mapIdleBtn"); return { has: b.classList.contains("has"), bar: b.querySelector(".mib i").style.width }; });
  o.pop9h = await away(9);
  console.log(JSON.stringify(o));
  assert.strictEqual(o.pop2h, 0, "2 h away (not full): no popup");
  assert.ok(o.icon.vis && o.icon.has && !o.icon.full && /^2[0-9]%$/.test(o.icon.bar), "icon shows a part-full bucket");
  assert.ok(/Idle rewards/.test(o.popTxt) && /2\d% full/.test(o.popTxt), "icon opens the bucket");
  assert.ok(o.gained >= 76 && o.gained <= 84 && !o.after.has && o.after.bar === "0%", "collected 2 h worth, icon empty");
  assert.strictEqual(o.pop9h, 1, "full bucket: popup");
  console.log("errs", errs); assert.deepStrictEqual(errs, []); console.log("ALL OK"); await b.close();
})().catch((e) => { console.error("FAIL", e.message); process.exit(1); });
