/* v1010: research shown as a tree (hex nodes + lines, rows of 1 and 2); tapping a node opens a popup with Now / Next / Research; states max / can / locked / running. Run: node dev/simfork/g230_research_tree.js */
const fs = require("fs"), path = require("path"), assert = require("assert");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require(process.env.PW_PATH || "/opt/npm-tools/node_modules/playwright");
const CHROME = process.env.CHROME_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const FAKE = fs.readFileSync(path.join(ROOT, "dev/tests/fakefb.js"), "utf8"), GAME = fs.readFileSync(process.env.GAMEFILE || path.join(ROOT, "test/index.html"), "utf8");
const store = {}, call = require(path.join(ROOT, "dev/tests/fnrunner.js"))(store);
(async () => {
  const b = await chromium.launch({ executablePath: CHROME, args: ["--no-sandbox"] }), errs = [];
  const ctx = await b.newContext({ viewport: { width: 430, height: 932 } });
  await ctx.exposeFunction("__fbstore", (op, k, v) => { if (op === "set") store[k] = JSON.parse(v); else if (op === "del") delete store[k]; return JSON.stringify(store); });
  await ctx.exposeFunction("__fbcall", call);
  await ctx.route(/mojojo82\.github\.io/, (r) => r.fulfill({ status: 200, contentType: "text/html", body: GAME }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: FAKE }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*(auth|firestore|functions)-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: "" }));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
  const P = await ctx.newPage(); P.on("pageerror", (e) => errs.push(e.message));
  await P.goto("https://mojojo82.github.io/kingdom-strategy/test/"); await P.waitForSelector("#ksAuth .box");
  await P.fill("#ksE", "g230@test.dev"); await P.fill("#ksP", "secret123"); await P.click("#ksUp");
  await P.waitForSelector("#ksN", { timeout: 15000 }); await P.fill("#ksN", "Emp"); await P.click("#ksGo"); await P.waitForTimeout(5000);
  await P.evaluate(() => { const t = game.state.tech; t.pavedRoads = 10; t.energonSiphon = 2; game.state.researchPoints = 5e6; activeTechCategory = "growth"; setScreen("city"); });
  await P.waitForTimeout(600);
  await P.evaluate(() => { const el = [...document.querySelectorAll("*")].find((e) => e.children.length === 0 && /📚/.test(e.textContent) && /Research$/.test(e.textContent.trim())); el.click(); }); /* the city's Research tab, like a player */
  await P.waitForTimeout(800);
  const o = {};
  o.tree = await P.evaluate(() => { const n = [...document.querySelectorAll("#techList .rt-node")]; const cls = {}; n.forEach((e) => { cls[e.dataset.k] = e.className.replace("rt-node", "").trim(); });
    return { nodes: n.length, growth: Object.keys(TECH_DEFS).filter((k) => TECH_DEFS[k].category === "growth").length, cls, paths: document.querySelectorAll("#techList .rt-lines path").length, rowsTop: [...new Set(n.map((e) => e.style.top))].length }; });
  const before = await P.evaluate(() => document.querySelector("#techList .rt-board"));
  await P.click(".rt-node[data-k=drillSergeant]"); await P.waitForTimeout(300);
  o.pop = await P.evaluate(() => document.getElementById("rtPop").innerText);
  await P.click("#rtGo"); await P.waitForTimeout(300);
  o.after = await P.evaluate(() => ({ queue: (game.state.researchQueue || {}).key, popShown: document.getElementById("rtPop").style.display, run: document.querySelector(".rt-node[data-k=drillSergeant]").className }));
  await P.waitForTimeout(1500);
  o.stable = await P.evaluate(() => { const t = document.querySelector("#techList [data-rt-time]"); return { timer: t && t.textContent }; });
  o.sameBoard = await P.evaluate(() => { const b1 = document.querySelector("#techList .rt-board"); window.__b1 = b1; return true; }); await P.waitForTimeout(2200); o.sameBoard = await P.evaluate(() => document.querySelector("#techList .rt-board") === window.__b1);
  await P.click(".rt-node[data-k=scholarlyPursuit]"); await P.waitForTimeout(300); o.lockedPop = await P.evaluate(() => document.getElementById("rtPop").innerText); await P.click(".rt-x"); await P.waitForTimeout(200);
  o.closed = await P.evaluate(() => document.getElementById("rtPop").style.display);
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "research_tree.png" });
  console.log(JSON.stringify(o));
  assert.ok(o.tree.nodes === o.tree.growth && o.tree.paths === o.tree.rowsTop - 1, "one node per Growth tech, lines between each pair of rows");
  assert.ok(/max/.test(o.tree.cls.pavedRoads) && /locked/.test(o.tree.cls.scholarlyPursuit) && /can/.test(o.tree.cls.drillSergeant), "node states: max / locked / can");
  assert.ok(/Drill Sergeant/.test(o.pop) && /Next level/.test(o.pop) && /Research \(/.test(o.pop), "popup: name, next level, Research button");
  assert.ok(o.after.queue === "drillSergeant" && o.after.popShown === "none" && /run/.test(o.after.run), "Research starts it, closes the popup, node shows it running");
  assert.ok(o.stable.timer && /⏳/.test(o.stable.timer), "running node shows its timer");
  assert.ok(o.sameBoard, "board isn't rebuilt every second (only the timer text changes)");
  assert.ok(/Requires Academy/.test(o.lockedPop) && !/Research \(/.test(o.lockedPop), "locked node: shows the requirement, no Research button");
  assert.strictEqual(o.closed, "none", "✕ closes");
  console.log("errs", errs); assert.deepStrictEqual(errs, []); console.log("ALL OK"); await b.close();
})().catch((e) => { console.error("FAIL", e.message); process.exit(1); });
