/* v1011: the Fortress tree uses the research-tree look (bronze board, hex nodes, cyan lines = unlock order) and a tap-for-details popup with Upgrade. Run: node dev/simfork/g231_fortress_tree.js */
const fs = require("fs"), path = require("path"), assert = require("assert");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require(process.env.PW_PATH || "/opt/npm-tools/node_modules/playwright");
const CHROME = process.env.CHROME_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const FAKE = fs.readFileSync(path.join(ROOT, "dev/tests/fakefb.js"), "utf8"), GAME = fs.readFileSync(process.env.GAMEFILE || path.join(ROOT, "test/index.html"), "utf8");
const store = {}, call = require(path.join(ROOT, "dev/tests/fnrunner.js"))(store);
(async () => {
  const b = await chromium.launch({ executablePath: CHROME, args: ["--no-sandbox"] }), errs = [];
  const ctx = await b.newContext({ viewport: { width: 430, height: 932 } });
  await ctx.exposeFunction("__fbstore", (op, k, v) => { if (op === "set") store[k] = JSON.parse(v); else if (op === "del") delete store[k]; return JSON.stringify(store); });
  await ctx.exposeFunction("__fbcall", call);
  await ctx.route(/mojojo82\.github\.io/, (r) => r.fulfill({ status: 200, contentType: "text/html", body: GAME }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: FAKE }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*(auth|firestore|functions)-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: "" }));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
  const P = await ctx.newPage(); P.on("pageerror", (e) => errs.push(e.message));
  await P.goto("https://mojojo82.github.io/kingdom-strategy/test/"); await P.waitForSelector("#ksAuth .box");
  await P.fill("#ksE", "g231@test.dev"); await P.fill("#ksP", "secret123"); await P.click("#ksUp");
  await P.waitForSelector("#ksN", { timeout: 15000 }); await P.fill("#ksN", "Emp"); await P.click("#ksGo"); await P.waitForTimeout(5000);
  await P.evaluate(() => { game.state.researchPoints = 2e6; game.state.fortressTech = {}; setScreen("more", "fortress"); });
  await P.waitForTimeout(600);
  const o = {};
  o.tree = await P.evaluate(() => { const n = [...document.querySelectorAll("#fortressBody .rt-node")]; const m = {}; n.forEach((e) => { m[e.dataset.k] = e.className.replace("rt-node", "").trim(); }); const TREE = fortressTreeOf(game.state.fortressTech);
    const edges = Object.keys(TREE).reduce((a, k) => a + TREE[k].parents.length, 0); return { nodes: n.length, defs: Object.keys(TREE).length, lines: document.querySelectorAll("#fortressBody .rt-lines polyline").length, edges, m, oldNodes: document.querySelectorAll("#fortressBody .ft-node").length }; });
  const first = await P.evaluate(() => Object.keys(fortressTreeOf({})).find((k) => fortressTreeOf({})[k].row === 0));
  await P.click('#fortressBody .rt-node[data-k="' + first + '"]'); await P.waitForTimeout(300);
  o.pop = await P.evaluate(() => document.getElementById("rtPop").innerText);
  const rp0 = await P.evaluate(() => game.state.researchPoints);
  await P.click("#ftUpBtn"); await P.waitForTimeout(300);
  o.up = await P.evaluate((k) => ({ lv: (game.state.fortressTech || {})[k] || 0, popOpen: document.getElementById("rtPop").style.display, popLv: /Level 1 \//.test(document.getElementById("rtPop").innerText) }), first);
  o.spent = rp0 - await P.evaluate(() => game.state.researchPoints);
  await P.click(".rt-x"); await P.waitForTimeout(200);
  const locked = Object.keys(o.tree.m).find((k) => /locked/.test(o.tree.m[k]));
  await P.click('#fortressBody .rt-node[data-k="' + locked + '"]'); await P.waitForTimeout(300); o.lockedPop = await P.evaluate(() => document.getElementById("rtPop").innerText); await P.click(".rt-x");
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "fortress_tree.png" });
  console.log(JSON.stringify(o));
  assert.ok(o.tree.nodes === o.tree.defs && o.tree.lines === o.tree.edges && o.tree.oldNodes === 0, "every node drawn in the new style, one line per unlock link");
  assert.ok(/can/.test(o.tree.m[first]) && !!locked, "top node researchable, lower ones locked");
  assert.ok(/Next level/.test(o.pop) && /Upgrade \(/.test(o.pop), "popup: next level + Upgrade with cost");
  assert.ok(o.up.lv === 1 && o.spent > 0 && o.up.popOpen === "flex" && o.up.popLv, "Upgrade levels it up, pays RP, popup stays open and updates");
  assert.ok(/Needs /.test(o.lockedPop) && /disabled/.test(await P.evaluate(() => document.getElementById("rtDetail").innerHTML)), "locked node says what it needs, Upgrade disabled");
  console.log("errs", errs); assert.deepStrictEqual(errs, []); console.log("ALL OK"); await b.close();
})().catch((e) => { console.error("FAIL", e.message); process.exit(1); });
