/* v1023: the Backpack - brown backpack on the World map and in Conquest; categories; speedups used on a running timer; Go for tickets/books. Run: node dev/simfork/g238_backpack.js */
const fs = require("fs"), path = require("path"), assert = require("assert");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require(process.env.PW_PATH || "/opt/npm-tools/node_modules/playwright");
const CHROME = process.env.CHROME_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const FAKE = fs.readFileSync(path.join(ROOT, "dev/tests/fakefb.js"), "utf8"), GAME = fs.readFileSync(process.env.GAMEFILE || path.join(ROOT, "test/index.html"), "utf8");
const store = {}, call = require(path.join(ROOT, "dev/tests/fnrunner.js"))(store);
(async () => {
  const b = await chromium.launch({ executablePath: CHROME, args: ["--no-sandbox"] }), errs = [];
  const ctx = await b.newContext({ viewport: { width: 430, height: 932 } });
  await ctx.exposeFunction("__fbstore", (op, k, v) => { if (op === "set") store[k] = JSON.parse(v); else if (op === "del") delete store[k]; return JSON.stringify(store); });
  await ctx.exposeFunction("__fbcall", call);
  await ctx.route(/mojojo82\.github\.io/, (r) => r.fulfill({ status: 200, contentType: "text/html", body: GAME }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: FAKE }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*(auth|firestore|functions)-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: "" }));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
  const P = await ctx.newPage(); P.on("pageerror", (e) => errs.push(e.message));
  await P.goto("https://mojojo82.github.io/kingdom-strategy/test/"); await P.waitForSelector("#ksAuth .box");
  await P.fill("#ksE", "g238@test.dev"); await P.fill("#ksP", "secret123"); await P.click("#ksUp");
  await P.waitForSelector("#ksN", { timeout: 15000 }); await P.fill("#ksN", "Emp"); await P.click("#ksGo"); await P.waitForTimeout(5000);
  await P.evaluate(() => { const st = game.state; st.speedups.construction_1h = 3; st.speedups.general_1h = 1; st.weaponTickets = 5; st.idle.conquestBooks = 40; st.resources.food = 1e6; st.resources.wood = 1e6; st.resources.stone = 1e6; st.resources.gold = 1e6; st.buildings.townhall.level = 7; window.__up = game.startUpgrade("townhall"); setScreen("world"); });
  await P.waitForTimeout(800);
  const o = {};
  o.worldBtn = await P.evaluate(() => { const r = document.getElementById("mapBagBtn").getBoundingClientRect(); return r.width > 0 && r.top > 60 && r.bottom < innerHeight; });
  await P.click("#mapBagBtn"); await P.waitForTimeout(400);
  o.tabs = await P.evaluate(() => [...document.querySelectorAll("#bagPop .bg-tab")].map((t) => t.textContent));
  o.speed = await P.evaluate(() => [...document.querySelectorAll("#bagPop .bg-it small")].map((t) => t.textContent));
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "backpack.png" });
  const fin0 = await P.evaluate(() => game.state.buildings.townhall.upgrading.finishAt);
  await P.evaluate(() => document.querySelector('#bagPop .bg-it[data-bi="su_con"]').click()); await P.waitForTimeout(200);
  await P.evaluate(() => document.querySelector("#bagPop [data-su]").click()); await P.waitForTimeout(400);
  o.used = await P.evaluate((f0) => ({ cut: Math.round((f0 - game.state.buildings.townhall.upgrading.finishAt) / 60000), left: game.state.speedups.construction_1h, shown: document.querySelector('#bagPop .bg-it[data-bi="su_con"] b').textContent }), fin0);
  await P.evaluate(() => document.querySelector('#bagPop [data-bc="items"]').click()); await P.waitForTimeout(200);
  o.items = await P.evaluate(() => [...document.querySelectorAll("#bagPop .bg-it small")].map((t) => t.textContent));
  await P.evaluate(() => document.querySelector('#bagPop [data-bc="res"]').click()); await P.waitForTimeout(200);
  o.res = await P.evaluate(() => document.querySelector("#bagPop .bg-grid").textContent);
  await P.evaluate(() => document.querySelector(".bg-x").click());
  await P.evaluate(() => setScreen("conquest")); await P.waitForTimeout(600);
  o.conq = await P.evaluate(() => { const bb = document.querySelector(".idle-bag-btn"); const r = bb && bb.getBoundingClientRect(); return !!r && r.width > 0; });
  await P.evaluate(() => document.querySelector(".idle-bag-btn").click()); await P.waitForTimeout(300);
  o.conqOpen = await P.evaluate(() => document.getElementById("bagPop").style.display);
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "backpack_conq.png" });
  console.log(JSON.stringify(o));
  assert.ok(o.worldBtn && o.conq && o.conqOpen === "flex", "backpack on the World map and in Conquest, both open it");
  assert.deepStrictEqual(o.tabs, ["Resources", "Speedups", "Items", "Heroes"]);
  assert.ok(o.speed.length === 2, "speedups listed");
  assert.ok(o.used.cut === 60 && o.used.left === 2 && o.used.shown === "x2", "using a construction speedup takes 1h off the Town Hall upgrade");
  assert.ok(o.items.length === 2 && /ticket/i.test(o.items[0]) && /Books/.test(o.items[1]), "tickets and books under Items");
  assert.ok(/No resource chests yet/.test(o.res), "Resources ready for chests");
  /* v1024: chests and packs */
  o.chest = await P.evaluate(() => { const st = game.state; ["custom_2", "supply_10000"].forEach((k) => game.addItem(k, 3)); game.addItem("res_wood_1000", 4); const f0 = st.resources.food, w0 = st.resources.wood;
    bagState.cat = "res"; bagState.sel = "custom_2"; bagOpen(); const tiles = [...document.querySelectorAll("#bagPop .bg-it")].map((t) => t.className.replace("bg-it", "").trim() + "|" + t.innerText.replace(/\s+/g, " "));
    document.querySelector("#bagPop [data-buse]").click(); const noPick = document.querySelector("#bagPop .bg-got").textContent, leftNoPick = st.items.custom_2;
    document.querySelector('#bagPop [data-bp="food"]').click(); document.querySelector('#bagPop [data-bq="1"]').click(); document.querySelector("#bagPop [data-buse]").click();
    const r1 = { food: st.resources.food - f0, left: st.items.custom_2, got: document.querySelector("#bagPop .bg-got").textContent };
    bagState.sel = "res_wood_1000"; bagRender(); document.querySelector('#bagPop [data-bq="max"]').click(); document.querySelector("#bagPop [data-buse]").click();
    const r2 = { wood: st.resources.wood - w0, left: st.items.res_wood_1000 || 0 };
    bagState.sel = "supply_10000"; bagRender(); document.querySelector("#bagPop [data-bdet]").click(); const odds = document.querySelector("#bagPop .bg-tg") ? document.querySelector("#bagPop .bg-tg").innerText : "";
    const tot0 = st.resources.food + st.resources.wood + st.resources.stone + st.resources.gold; document.querySelector("#bagPop [data-buse]").click(); const tot1 = st.resources.food + st.resources.wood + st.resources.stone + st.resources.gold;
    return { tiles, noPick, leftNoPick, r1, r2, odds, supplyGain: tot1 - tot0, supplyLeft: st.items.supply_10000 }; });
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "backpack_chests.png" });
  console.log(JSON.stringify(o.chest));
  assert.ok(o.chest.tiles[0].startsWith("r2") && /Lv\.2/.test(o.chest.tiles[0]), "custom chest first, blue (Lv.2) tile");
  assert.ok(/Pick a resource/.test(o.chest.noPick) && o.chest.leftNoPick === 3, "a Custom chest needs a pick first");
  assert.ok(o.chest.r1.food === 200000 && o.chest.r1.left === 1 && /\+200K Food/.test(o.chest.r1.got), "2x Lv.2 Custom → 200K Food");
  assert.ok(o.chest.r2.wood === 4000 && o.chest.r2.left === 0, "Max uses all 4 x 1K Wood");
  assert.ok(/35%/.test(o.chest.odds) && o.chest.supplyGain === 10000 && o.chest.supplyLeft === 2, "supply chest: Details shows the odds, gives 10K of one resource");
  console.log("errs", errs); assert.deepStrictEqual(errs, []); console.log("ALL OK"); await b.close();
})().catch((e) => { console.error("FAIL", e.message); process.exit(1); });
