/* v1027/v1028: troop training cap per batch (Kingshot curve x7.5 + Camp Expansion research) and the Train box starts at the most you can train now. Run: node dev/simfork/g240_train_cap.js */
const fs = require("fs"), path = require("path"), assert = require("assert");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require(process.env.PW_PATH || "/opt/npm-tools/node_modules/playwright");
const CHROME = process.env.CHROME_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const FAKE = fs.readFileSync(path.join(ROOT, "dev/tests/fakefb.js"), "utf8"), GAME = fs.readFileSync(process.env.GAMEFILE || path.join(ROOT, "test/index.html"), "utf8");
const store = {}, call = require(path.join(ROOT, "dev/tests/fnrunner.js"))(store);
(async () => {
  const b = await chromium.launch({ executablePath: CHROME, args: ["--no-sandbox"] }), errs = [];
  const ctx = await b.newContext({ viewport: { width: 430, height: 932 } });
  await ctx.exposeFunction("__fbstore", (op, k, v) => { if (op === "set") store[k] = JSON.parse(v); else if (op === "del") delete store[k]; return JSON.stringify(store); });
  await ctx.exposeFunction("__fbcall", call);
  await ctx.route(/mojojo82\.github\.io/, (r) => r.fulfill({ status: 200, contentType: "text/html", body: GAME }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: FAKE }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*(auth|firestore|functions)-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: "" }));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
  const P = await ctx.newPage(); P.on("pageerror", (e) => errs.push(e.message));
  await P.goto("https://mojojo82.github.io/kingdom-strategy/test/"); await P.waitForSelector("#ksAuth .box");
  await P.fill("#ksE", "g240@test.dev"); await P.fill("#ksP", "secret123"); await P.click("#ksUp");
  await P.waitForSelector("#ksN", { timeout: 15000 }); await P.fill("#ksN", "Emp"); await P.click("#ksGo"); await P.waitForTimeout(5000);
  await P.evaluate(() => { const st = game.state; ["food","wood","stone","gold"].forEach((r) => st.resources[r] = 1e7); st.buildings.barracks.level = 10; st.buildings.barracks.queue = []; setScreen("city", "troops"); renderTroops(); });
  await P.waitForTimeout(800);
  const o = {};
  o.cap = await P.evaluate(() => game.trainCap("barracks"));
  o.top = await P.evaluate(() => { const st = game.state, l = st.buildings.barracks.level; st.buildings.barracks.level = 30; const lv30 = game.trainCap("barracks"); st.tech.campExpansion = 10; const full = game.trainCap("barracks"); st.tech.campExpansion = 0; st.buildings.barracks.level = l; return { lv30, full }; });
  o.top = await P.evaluate(() => { const st = game.state, l = st.buildings.barracks.level; st.buildings.barracks.level = 30; const lv30 = game.trainCap("barracks"); st.tech.campExpansion = 10; const full = game.trainCap("barracks"); st.tech.campExpansion = 0; st.buildings.barracks.level = l; return { lv30, full }; });
  o.box = await P.evaluate(() => document.querySelector("#troopsList .train-n").value);
  await P.evaluate(() => document.getElementById("troopsList").scrollIntoView()); await P.waitForTimeout(200); await P.screenshot({ path: (process.env.OUT || "/tmp/") + "train_cap.png" });
  o.over = await P.evaluate(() => { const r = game.queueTraining("barracks", 9999, 1); return { ok: r.ok, n: game.state.buildings.barracks.queue[0].count }; });
  o.poor = await P.evaluate(() => { const st = game.state; const u = TROOP_DEFS[troopKey("infantry", 1)].cost; ["food","wood","stone","gold"].forEach((r) => st.resources[r] = u[r] ? u[r] * 7 + 1 : 1e6); troopTrainCount.infantry = 0; renderTroops(); return { box: document.querySelector("#troopsList .train-n").value, txt: document.querySelector("#troopsList").innerText.match(/resources for \d+/) + "" }; });
  o.minus = await P.evaluate(() => { const bs = [...document.querySelectorAll("#troopsList .train-step")]; bs[0].click(); return document.querySelector("#troopsList .train-n").value; });
  console.log(JSON.stringify(o), errs);
  assert.strictEqual(o.cap, 420, "Lv10 barracks cap 420 (56 x 7.5)");
  assert.deepStrictEqual(o.top, { lv30: 1568, full: 2068 }, "Lv30 1,568; with Camp Expansion 10 = 2,068");
  assert.strictEqual(o.box, "420", "box pre-filled with the cap when rich");
  assert.ok(o.over.ok && o.over.n === 420, "asking for 9999 trains only the cap");
  assert.strictEqual(o.poor.box, "7", "box pre-filled with what you can afford");
  assert.ok(/resources for 7/.test(o.poor.txt), "shows resources limit");
  assert.strictEqual(o.minus, "6", "minus button steps down");
  assert.deepStrictEqual(errs, []);
  await b.close(); console.log("g240 OK");
})().catch((e) => { console.error(e); process.exit(1); });
