/* v1042: Conquest's 6 bottom-left boxes show equipped cards; admin dev switch turns card effects off (still equipped/shown). Run: node dev/simfork/g246_card_slots.js */
const fs = require("fs"), path = require("path"), assert = require("assert");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require(process.env.PW_PATH || "/opt/npm-tools/node_modules/playwright");
const CHROME = process.env.CHROME_PATH || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const FAKE = fs.readFileSync(path.join(ROOT, "dev/tests/fakefb.js"), "utf8"), GAME = fs.readFileSync(process.env.GAMEFILE || path.join(ROOT, "test/index.html"), "utf8");
const store = {}, call = require(path.join(ROOT, "dev/tests/fnrunner.js"))(store);
(async () => {
  const b = await chromium.launch({ executablePath: CHROME, args: ["--no-sandbox"] }), errs = [];
  const ctx = await b.newContext({ viewport: { width: 430, height: 932 } });
  await ctx.exposeFunction("__fbstore", (op, k, v) => { if (op === "set") store[k] = JSON.parse(v); else if (op === "del") delete store[k]; return JSON.stringify(store); });
  await ctx.exposeFunction("__fbcall", call);
  await ctx.route(/mojojo82\.github\.io/, (r) => r.fulfill({ status: 200, contentType: "text/html", body: GAME }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: FAKE }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*(auth|firestore|functions)-compat\.js/, (r) => r.fulfill({ status: 200, contentType: "application/javascript", body: "" }));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, (r) => r.abort());
  const P = await ctx.newPage(); P.on("pageerror", (e) => errs.push(e.message));
  await P.goto("https://mojojo82.github.io/kingdom-strategy/test/"); await P.waitForSelector("#ksAuth .box");
  await P.fill("#ksE", "g246@test.dev"); await P.fill("#ksP", "secret123"); await P.click("#ksUp");
  await P.waitForSelector("#ksN", { timeout: 15000 }); await P.fill("#ksN", "Emp"); await P.click("#ksGo"); await P.waitForTimeout(5000);
  const o = {};
  await P.evaluate(() => { game.state.equippedCards = [0, 4, 13, 27]; setScreen("conquest"); render(); }); await P.waitForTimeout(1200);
  o.boxes = await P.evaluate(() => { const top = document.getElementById("idlePowerSlots"); const bx = [...top.querySelectorAll(":scope > .power-slot"), ...top.nextElementSibling.querySelectorAll(":scope > .power-slot")]; return bx.map((b) => (b.querySelector("img") ? "art" : "-") + (b.getBoundingClientRect().width > 30 ? "" : "?")); });
  o.weapons = await P.evaluate(() => !!document.querySelector("#idlePowerSlots .idle-weapon-slots"));
  await P.screenshot({ path: (process.env.OUT || "/tmp/") + "cq_cards.png" });
  o.fxOn = await P.evaluate(() => equippedCardEffects(game.state).length);
  o.fxOff = await P.evaluate(() => { KS_BACKEND.isAdmin = true; localStorage.setItem(DEV_CARDS_OFF_KEY, "1"); return { mine: equippedCardEffects(game.state).length, sim: equippedCardEffects({ equippedCards: game.state.equippedCards.slice(), cards: game.state.cards }).length, stillEquipped: game.state.equippedCards.length, shown: document.querySelectorAll("#idlePowerSlots .cq-card img, #idlePowerSlots + .ps-row2 .cq-card img").length }; });
  o.nonAdmin = await P.evaluate(() => { KS_BACKEND.isAdmin = false; const n = equippedCardEffects(game.state).length; KS_BACKEND.isAdmin = true; return n; });
  o.back = await P.evaluate(() => { localStorage.setItem(DEV_CARDS_OFF_KEY, "0"); return equippedCardEffects(game.state).length; });
  o.unequip = await P.evaluate(() => { game.state.equippedCards = [13]; render(); return document.querySelectorAll("#idlePowerSlots .cq-card, #idlePowerSlots + .ps-row2 .cq-card").length; });
  console.log(JSON.stringify(o), errs);
  assert.deepStrictEqual(o.boxes, ["art", "art", "art", "art", "-", "-"], "4 equipped cards fill the first 4 of 6 boxes");
  assert.ok(o.weapons, "weapon slots still there");
  assert.ok(o.fxOn >= 2, "equipped cards have effects");
  assert.deepStrictEqual(o.fxOff, { mine: 0, sim: o.fxOn, stillEquipped: 4, shown: 4 }, "dev switch: no effects for you, still equipped + shown; simulators unaffected");
  assert.strictEqual(o.nonAdmin, o.fxOn, "only works for admins");
  assert.strictEqual(o.back, o.fxOn, "switch off -> effects back");
  assert.strictEqual(o.unequip, 1, "boxes follow equip changes");
  assert.deepStrictEqual(errs, []);
  await b.close(); console.log("g246 OK");
})().catch((e) => { console.error(e); process.exit(1); });
